name: 1 - Worflow connexion Azure # Nom du Workflow

on: # declenchement du workflows
  workflow_dispatch: # manuel https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

jobs:

  connexion-azure: # Nom du job
    runs-on: ubuntu-latest # Runner machine qui execute le workflow

  steps:


